If python is broken due to libstdc++ changes or whatever, make sure gcc-config still works somewhat sanely.

diff --git a/gcc-config b/gcc-config
--- a/gcc-config
+++ b/gcc-config
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Copyright 1999-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: gentoo-x86/sys-devel/gcc-config/files/gcc-config-1.3.10,v 1.11 2005/04/28 23:42:25 vapier Exp $
+# $Header: gentoo-x86/sys-devel/gcc-config/files/gcc-config-1.3.11,v 1.1 2005/06/06 03:58:40 vapier Exp $
 
 trap ":" INT QUIT TSTP
 
@@ -18,6 +18,7 @@ Change the current cc/gcc profile, or give info about profiles.
 
 Options:
   -O, --use-old              Use the old profile if one was selected.
+  -f, --force                Make sure all config files are regenerated.
   -P, --use-portage-chost    Only set to given profile if its CHOST is the
                              same as that set for portage in /etc/make.conf
                              (or one of other portage config files...).
@@ -67,11 +68,14 @@ cmd_setup() {
 	MV=$(find_path mv)
 	LN=$(find_path ln)
 	CAT=$(find_path cat)
+	ENV=$(find_path env)
+	SED=$(find_path sed)
 	AWK=$(find_path gawk)
 	GREP=$(find_path grep)
 	FIND=$(find_path find)
 	CHMOD=$(find_path chmod)
 	TOUCH=$(find_path touch)
+	PYTHON=$(find_path python)
 	PORTAGEQ=$(find_path portageq)
 	ENV_UPDATE=$(find_path env-update)
 }
@@ -79,7 +83,12 @@ cmd_setup() {
 get_real_chost() {
 	[[ -n ${REAL_CHOST} ]] && return 0
 
-	export REAL_CHOST=$(env -i ${PORTAGEQ} envvar CHOST)
+	# make sure portage isnt broken
+	if ${PYTHON} -V &>/dev/null ; then
+		export REAL_CHOST=$(${ENV} -i ${PORTAGEQ} envvar CHOST 2>/dev/null)
+	else
+		export REAL_CHOST=$(source "${ROOT}"/etc/make.conf ; echo ${CHOST})
+	fi
 
 	if [[ -z ${REAL_CHOST} ]] ; then
 		eerror "$0: Could not get portage CHOST!"
@@ -253,8 +262,18 @@ switch_profile() {
 		unset libdir
 	fi
 
-	if [[ ${ROOT} == "/" ]] && [[ ${OLD_CC_COMP} != ${CC_COMP} ]] ; then
-		${ENV_UPDATE} &>/dev/null
+	if [[ ${ROOT} == "/" ]] && [[ ${OLD_CC_COMP} != ${CC_COMP} || ${FORCE} == "yes" ]] ; then
+		# in case python is broken ...
+		if ! ${ENV_UPDATE} &>/dev/null ; then
+			echo ""
+			ewarn "env-update failed to work properly; making sure ld.so.conf paths"
+			ewarn "are setup properly.  Please rerun gcc-config with the -f option."
+			echo ""
+			${GREP} -h ^LDPATH= "${ROOT}"/etc/env.d/05gcc \
+				| ${SED} -e 's:^LDPATH=::' -e 's:"::g' -e 's|:|\n|g' \
+				>> /etc/ld.so.conf
+			ldconfig
+		fi
 	fi
 
 	eend 0
@@ -378,6 +397,7 @@ get_stdcxx_incdir() {
 NEED_ACTION="yes"
 DOIT="switch_profile"
 CHECK_CHOST="no"
+FORCE="no"
 
 CC_COMP=
 [[ -z ${ROOT} ]] && ROOT="/"
@@ -392,6 +412,9 @@ for x in "$@" ; do
 			if get_current_profile &>/dev/null ; then
 				CC_COMP="$(get_current_profile)"
 			fi
+			;;
+		-f|--force)
+			FORCE="yes"
 			;;
 		-P|--use-portage-chost)
 			CHECK_CHOST="yes"
