Use /lib/gentoo/functions.sh instead of /etc/init.d/functions.sh.
URL: https://bugs.gentoo.org/504118
Signed-off-by: Ryan Hill <rhill@gentoo.org>
Signed-off-by: Lars Wendler <polynomial-c@gentoo.org>

diff --git a/gcc-config b/gcc-config
--- a/gcc-config
+++ b/gcc-config
@@ -18,8 +18,9 @@ cd /
 trap ":" INT QUIT TSTP
 
 argv0=${0##*/}
-source "${EPREFIX}"/etc/init.d/functions.sh || {
-	echo "${argv0}: Could not source ${EPREFIX}/etc/init.d/functions.sh!" 1>&2
+functions_script="${EPREFIX}/lib/gentoo/functions.sh"
+source ${functions_script} || {
+	echo "${argv0}: Could not source ${functions_script}!" 1>&2
 	exit 1
 }
 esyslog() { :; }
